### ISSUE TITLE
[Question] Authentification

### ISSUE THREAD

**Issue by HollishKid** [crashoz/react-minecraft#1]
L'authentification demandée n'est pas régulière. Je peux éteindre mon PC, puis me reconnecter sur la page sans avoir besoin de m'identifier.
Est-ce que ça pourrait poser un problème de sécurité ?

**Comment by crashoz** [comment]
C'est un mécanisme de persistance de l'authentification, la session est valable au maximum pour une journée. Pas d'inquiétude, c'est tout à fait normal.
